<div>
	
	<h2><a href=""><i class="fas fa-home icon"></i>Acccueil</a></h2>
	<ul class="post">
		<?php foreach ($posts  as $post): ?>

		<li class="post-list">
			<p><a href="show_post.php?id=<?=$post['Id']?>"><h3><i class="fas fa-hand-point-right"></i><?=htmlspecialchars($post['Title'])?></h3></a></p>
			<p><?=htmlspecialchars(substr($post['Contents'],0,100))?> []</p>
			<p><span>Redigé par <?=htmlspecialchars($post['FirstName'])?> <?=htmlspecialchars($post['LastName'])?> le
			 <?=htmlspecialchars($post['CreationTimestamp'])?></span></p>
		</li>

	<?php endforeach; ?>
	</ul>

</div>