<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Layout.phtml</title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
	<link rel="stylesheet" type="text/css" href="css/normalize-3.0.3.min.css">
	<link rel="stylesheet" type="text/css" href="css/blog-theme.css">
	
	<link rel="stylesheet" type="text/css" href="css/ui-form.css">
	<link rel="stylesheet" type="text/css" href="css/blog-main.css">
	<link rel="stylesheet" type="text/css" href="css/ui-button.css">
	<script
		  src="https://code.jquery.com/jquery-3.4.1.min.js"
		  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
		  crossorigin="anonymous">
  </script>
</head>
<body>
<header>
	<h1><a href="index.php"><i class="fas fa-microphone icon"></i>ENCORE UN Blog ?! NON MAISSALLO</a></h1>
	<nav><a href="admin.php"><i class="fas fa-cogs icon"></i>Administration</a></nav>

</header>

<main>

	<?php 

		include $template.".phtml";
	?>

</main>


<footer>
	<p>Le blog des èleves de la 3W Academy</p>
</footer>
<script src="js/main.js">
		
	


</script>
</body>
</html>